# Generated by Django 5.2.15 on 2026-07-29 15:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegimeState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("regime", models.CharField(db_index=True, max_length=60)),
                (
                    "probability",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("as_of", models.DateTimeField(db_index=True)),
                ("indicators", models.JSONField(default=dict)),
                ("alternatives", models.JSONField(default=dict)),
                ("model_metadata", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["-as_of", "regime"], name="signals_reg_as_of_e04c91_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="RegimeTransitionAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("rationale", models.TextField(blank=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_alerts",
                        to="signals.regimestate",
                    ),
                ),
                (
                    "previous_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_alerts",
                        to="signals.regimestate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConvictionScorePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("level", models.CharField(max_length=30)),
                (
                    "action_signal",
                    models.CharField(
                        choices=[
                            ("strong_buy", "Strong buy"),
                            ("buy", "Buy"),
                            ("hold", "Hold"),
                            ("reduce", "Reduce"),
                            ("sell", "Sell"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_return_low", models.FloatField(blank=True, null=True)),
                ("expected_return_high", models.FloatField(blank=True, null=True)),
                ("horizon_days", models.PositiveIntegerField(blank=True, null=True)),
                ("component_scores", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=list)),
                ("caveats", models.JSONField(default=list)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conviction_scores",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("analysis_run_id", "version"), name="uq_conviction_run_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SignalAgreementMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("signal_stances", models.JSONField(default=dict)),
                ("agreements", models.JSONField(default=list)),
                ("conflicts", models.JSONField(default=list)),
                ("agreement_ratio", models.FloatField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_agreements",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("analysis_run_id", "version"),
                        name="uq_signal_agreement_run_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TechnicalSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("signal_type", models.CharField(db_index=True, max_length=80)),
                ("timeframe", models.CharField(max_length=20)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("value", models.FloatField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_signals",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "signal_type", "-observed_at"],
                        name="signals_tec_ticker__f2b92b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticker", "signal_type", "timeframe", "observed_at", "version"),
                        name="uq_technical_signal_observation",
                    )
                ],
            },
        ),
    ]
