# Generated by Django 5.2.15 on 2026-07-30 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_initial"),
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="convictionscorepackage",
            name="run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conviction_score",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="signalagreementmatrix",
            name="run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signal_agreement",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AlterField(
            model_name="convictionscorepackage",
            name="action_signal",
            field=models.CharField(
                choices=[
                    ("strong_buy", "Strong Buy"),
                    ("buy", "Buy"),
                    ("accumulate", "Accumulate"),
                    ("hold", "Hold"),
                    ("reduce", "Reduce"),
                    ("sell", "Sell"),
                    ("strong_sell", "Strong Sell"),
                    ("not_buy", "Not Buy"),
                    ("not_sell", "Not Sell"),
                ],
                max_length=20,
            ),
        ),
    ]
