# Generated by Django 5.2.15 on 2026-07-29 15:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalystRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("catalyst_type", models.CharField(db_index=True, max_length=60)),
                ("expected_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("impact", models.CharField(blank=True, max_length=30)),
                ("evidence", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalysts",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EarningsQualityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("accrual_metrics", models.JSONField(default=dict)),
                ("cash_conversion_metrics", models.JSONField(default=dict)),
                ("accounting_flags", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=list)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings_quality_reports",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PeerAnalysisReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("comparison_dimensions", models.JSONField(default=dict)),
                ("relative_ranking", models.JSONField(default=dict)),
                ("differentiators", models.JSONField(default=list)),
                ("summary", models.TextField()),
                ("evidence", models.JSONField(default=list)),
                (
                    "peer_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_reports",
                        to="market_data.peergroup",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_analysis_reports",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BullBearDecisionMemo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("bull_case", models.TextField()),
                ("bear_case", models.TextField()),
                ("base_case", models.TextField()),
                ("key_disagreements", models.JSONField(default=list)),
                ("falsifiers", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=list)),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_memos",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("analysis_run_id", "version"), name="uq_decision_memo_run_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecialistReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("specialist_type", models.CharField(db_index=True, max_length=50)),
                ("thesis", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("evidence", models.JSONField(default=list)),
                ("assumptions", models.JSONField(default=list)),
                ("limitations", models.JSONField(default=list)),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_reports",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "specialist_type", "-generated_at"],
                        name="research_sp_ticker__0cf47b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("analysis_run_id", "specialist_type", "version"),
                        name="uq_specialist_report_run_type_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ValuationOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("analysis_run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("methodology", models.CharField(max_length=80)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "bear_value",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
                ),
                ("base_value", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "bull_value",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
                ),
                ("assumptions", models.JSONField(default=dict)),
                ("sensitivities", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=list)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_outputs",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "-created_at"], name="research_va_ticker__1fc12b_idx"
                    )
                ],
            },
        ),
    ]
