# Generated by Django 5.2.15 on 2026-07-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalystrecord",
            name="actual_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalystrecord",
            name="alert_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalystrecord",
            name="is_thesis_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalystrecord",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalystrecord",
            name="outcome_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="catalystrecord",
            name="outcome_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("occurred", "Occurred"),
                    ("failed", "Failed"),
                    ("delayed", "Delayed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
