# Generated by Django 5.2.15 on 2026-07-30 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_initial"),
        ("research", "0002_catalystrecord_actual_at_catalystrecord_alert_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="debate_rounds",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="material_unknowns",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="missing_evidence",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="output_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="premortem",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_memo",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="bullbeardecisionmemo",
            name="weak_assumptions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="catalystrecord",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalysts",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="peeranalysisreport",
            name="run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peer_report",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="specialistreport",
            name="input_references",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="specialistreport",
            name="output_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="specialistreport",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialist_reports",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="specialistreport",
            name="stance",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
