# Generated by Django 5.2.15 on 2026-07-29 15:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MacroIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("series_id", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateField(db_index=True)),
                ("value", models.DecimalField(decimal_places=10, max_digits=28, null=True)),
                ("frequency", models.CharField(blank=True, max_length=30)),
                ("unit", models.CharField(blank=True, max_length=80)),
                ("is_preliminary", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["series_id", "-observed_at"], name="market_data_series__c43c0f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series_id", "observed_at", "source_type"),
                        name="uq_macro_series_date_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("industry", models.CharField(blank=True, max_length=160)),
                ("classification_system", models.CharField(default="GICS", max_length=30)),
                ("code", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ("name", "industry"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "industry", "classification_system"),
                        name="uq_sector_classification",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(default="US", max_length=32)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("isin", models.CharField(blank=True, db_index=True, max_length=12)),
                ("cusip", models.CharField(blank=True, db_index=True, max_length=9)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("equity", "Equity"),
                            ("etf", "ETF"),
                            ("fund", "Fund"),
                            ("index", "Index"),
                            ("adr", "ADR"),
                            ("other", "Other"),
                        ],
                        default="equity",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickers",
                        to="market_data.sector",
                    ),
                ),
            ],
            options={
                "ordering": ("symbol", "exchange"),
            },
        ),
        migrations.CreateModel(
            name="PeerGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=160)),
                ("methodology", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "peers",
                    models.ManyToManyField(
                        blank=True, related_name="peer_groups", to="market_data.ticker"
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_peer_groups",
                        to="market_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OHLCVBar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1m", "1 minute"),
                            ("5m", "5 minutes"),
                            ("15m", "15 minutes"),
                            ("1h", "1 hour"),
                            ("1d", "1 day"),
                            ("1wk", "1 week"),
                            ("1mo", "1 month"),
                        ],
                        default="1d",
                        max_length=8,
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "adjusted_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=24,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlcv_bars",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ("ticker", "-timestamp"),
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("headline", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("categories", models.JSONField(blank=True, default=list)),
                (
                    "ticker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_items",
                        to="market_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsiderTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("owner_name", models.CharField(max_length=255)),
                ("owner_relationship", models.CharField(blank=True, max_length=120)),
                ("transaction_date", models.DateField(db_index=True)),
                ("transaction_code", models.CharField(blank=True, max_length=20)),
                (
                    "shares",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
                ),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True),
                ),
                ("is_direct_ownership", models.BooleanField(null=True)),
                ("accession_number", models.CharField(blank=True, max_length=40)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insider_transactions",
                        to="market_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("income", "Income statement"),
                            ("balance_sheet", "Balance sheet"),
                            ("cash_flow", "Cash flow"),
                            ("metrics", "Financial metrics"),
                        ],
                        max_length=30,
                    ),
                ),
                ("period_end", models.DateField(db_index=True)),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                ("fiscal_quarter", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("accession_number", models.CharField(blank=True, max_length=40)),
                ("values", models.JSONField(default=dict)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_statements",
                        to="market_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("headquarters_country", models.CharField(blank=True, max_length=80)),
                (
                    "market_cap",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
                ),
                (
                    "shares_outstanding",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
                ),
                ("ipo_date", models.DateField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "ticker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="ticker",
            index=models.Index(
                fields=["symbol", "is_active"], name="market_data_symbol_ee7543_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticker",
            constraint=models.UniqueConstraint(
                fields=("symbol", "exchange"), name="uq_ticker_symbol_exchange"
            ),
        ),
        migrations.AddConstraint(
            model_name="peergroup",
            constraint=models.UniqueConstraint(
                fields=("ticker", "name", "version"), name="uq_peer_group_version"
            ),
        ),
        migrations.AddIndex(
            model_name="ohlcvbar",
            index=models.Index(
                fields=["ticker", "interval", "-timestamp"], name="market_data_ticker__0e7d59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ohlcvbar",
            constraint=models.UniqueConstraint(
                fields=("ticker", "timestamp", "interval", "source_type"),
                name="uq_ohlcv_ticker_time_interval_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="ohlcvbar",
            constraint=models.CheckConstraint(
                condition=models.Q(("high__gte", models.F("low"))), name="ck_ohlcv_high_gte_low"
            ),
        ),
        migrations.AddIndex(
            model_name="newsitem",
            index=models.Index(
                fields=["-published_at", "publisher"], name="market_data_publish_80d205_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.UniqueConstraint(
                fields=("content_hash", "source_type"), name="uq_news_hash_source"
            ),
        ),
        migrations.AddIndex(
            model_name="insidertransaction",
            index=models.Index(
                fields=["ticker", "-transaction_date"], name="market_data_ticker__944939_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="insidertransaction",
            constraint=models.UniqueConstraint(
                fields=("ticker", "content_hash", "source_type"), name="uq_insider_tx_hash_source"
            ),
        ),
        migrations.AddIndex(
            model_name="financialstatement",
            index=models.Index(
                fields=["ticker", "statement_type", "-period_end"],
                name="market_data_ticker__e61f37_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialstatement",
            constraint=models.UniqueConstraint(
                fields=("ticker", "statement_type", "period_end", "source_type"),
                name="uq_fin_stmt_period_source",
            ),
        ),
    ]
