# Generated by Django 5.2.15 on 2026-07-30 06:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
        ("orchestrator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionSizingRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("methodology", models.CharField(max_length=60)),
                ("portfolio_weight_pct", models.DecimalField(decimal_places=6, max_digits=10)),
                ("num_shares", models.PositiveBigIntegerField(default=0)),
                ("dollar_amount", models.DecimalField(decimal_places=2, max_digits=24)),
                ("entry_tranches", models.PositiveSmallIntegerField(default=1)),
                ("risk_budget_contribution", models.DecimalField(decimal_places=8, max_digits=12)),
                ("incremental_risk", models.JSONField(default=dict)),
                ("assumptions", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScenarioAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("scenario_type", models.CharField(default="user_defined", max_length=50)),
                ("inputs", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("worst_impact", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExitStrategyPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=24)),
                ("stop_loss_price", models.DecimalField(decimal_places=8, max_digits=24)),
                ("stop_loss_pct", models.FloatField()),
                ("profit_targets", models.JSONField(default=list)),
                ("trailing_stop", models.JSONField(default=dict)),
                ("thesis_invalidation_triggers", models.JSONField(default=list)),
                ("time_based_review_date", models.DateTimeField()),
                (
                    "current_price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
                ),
                ("trigger_type", models.CharField(blank=True, max_length=60)),
                ("trigger_details", models.JSONField(default=dict)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_package",
                        to="orchestrator.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdeaRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("rank", models.PositiveIntegerField()),
                ("score", models.FloatField()),
                ("criteria_scores", models.JSONField(default=dict)),
                ("rationale", models.TextField(blank=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_rankings",
                        to="orchestrator.analysisrun",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_rankings",
                        to="market_data.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ("rank",),
            },
        ),
        migrations.CreateModel(
            name="PMRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("strong_buy", "Strong Buy"),
                            ("buy", "Buy"),
                            ("accumulate", "Accumulate"),
                            ("hold", "Hold"),
                            ("reduce", "Reduce"),
                            ("sell", "Sell"),
                            ("strong_sell", "Strong Sell"),
                            ("not_buy", "Not Buy"),
                            ("not_sell", "Not Sell"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "conviction",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                ("rationale", models.TextField()),
                ("expected_return", models.JSONField(default=dict)),
                ("position_size", models.JSONField(default=dict)),
                ("entry_plan", models.JSONField(default=list)),
                ("exit_conditions", models.JSONField(default=dict)),
                (
                    "time_horizon",
                    models.CharField(
                        choices=[
                            ("tactical", "Tactical"),
                            ("medium_term", "Medium Term"),
                            ("strategic", "Strategic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("catalysts", models.JSONField(default=list)),
                ("portfolio_fit", models.TextField()),
                ("capital_allocation_guidance", models.TextField()),
                ("conditions_precedent", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=list)),
                ("assumptions", models.JSONField(default=list)),
                ("limitations", models.JSONField(default=list)),
                ("review_rationale", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="orchestrator.analysisrun",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pm_recommendations",
                        to="market_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceAttributionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("measurement_period", models.CharField(max_length=30)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=24)),
                ("exit_price", models.DecimalField(decimal_places=8, max_digits=24)),
                ("realized_return", models.FloatField()),
                ("benchmark_return", models.FloatField(default=0)),
                ("excess_return", models.FloatField(default=0)),
                ("hit", models.BooleanField()),
                ("risk_adjusted_return", models.FloatField(blank=True, null=True)),
                ("agent_attribution", models.JSONField(default=dict)),
                ("signal_decay", models.JSONField(default=dict)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="portfolio.pmrecommendation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioConstructionOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("methodology", models.CharField(max_length=60)),
                ("target_allocations", models.JSONField(default=dict)),
                ("current_allocations", models.JSONField(default=dict)),
                ("constraints", models.JSONField(default=dict)),
                ("expected_metrics", models.JSONField(default=dict)),
                ("rebalance_required", models.BooleanField(default=False)),
                ("rebalance_trades", models.JSONField(default=list)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_construction",
                        to="orchestrator.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
