# Generated by Django 5.2.15 on 2026-07-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orchestrator", "0001_initial"),
        ("portfolio", "0001_initial"),
        ("risk_compliance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioconstructionoutput",
            name="portfolio_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="construction_outputs",
                to="risk_compliance.portfoliostate",
            ),
        ),
        migrations.AddField(
            model_name="positionsizingrecommendation",
            name="analysis_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizing_recommendation",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="scenarioanalysisresult",
            name="analysis_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_results",
                to="orchestrator.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="scenarioanalysisresult",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scenarioanalysisresult",
            name="portfolio_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_results",
                to="risk_compliance.portfoliostate",
            ),
        ),
        migrations.AddConstraint(
            model_name="idearanking",
            constraint=models.UniqueConstraint(
                fields=("analysis_run", "ticker", "version"),
                name="uq_idea_ranking_run_ticker_version",
            ),
        ),
        migrations.AddIndex(
            model_name="pmrecommendation",
            index=models.Index(
                fields=["ticker", "status", "-created_at"], name="portfolio_p_ticker__be6283_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="performanceattributionrecord",
            constraint=models.UniqueConstraint(
                fields=("recommendation", "measurement_period", "version"),
                name="uq_attribution_recommendation_period_version",
            ),
        ),
    ]
