# Generated by Django 5.2.15 on 2026-07-29 13:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditTrailRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("actor_label", models.CharField(blank=True, editable=False, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("override", "Override"),
                            ("escalate", "Escalate"),
                            ("execute", "Execute"),
                            ("request", "HTTP Request"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        editable=False,
                        max_length=24,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, editable=False, max_length=100)),
                (
                    "resource_type",
                    models.CharField(blank=True, db_index=True, editable=False, max_length=100),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, editable=False, max_length=255),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, editable=False, max_length=64),
                ),
                ("method", models.CharField(blank=True, editable=False, max_length=10)),
                ("path", models.CharField(blank=True, editable=False, max_length=512)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("user_agent", models.CharField(blank=True, editable=False, max_length=512)),
                ("summary", models.TextField(blank=True, editable=False)),
                ("metadata", models.JSONField(blank=True, default=dict, editable=False)),
                ("previous_values", models.JSONField(blank=True, default=dict, editable=False)),
                ("new_values", models.JSONField(blank=True, default=dict, editable=False)),
                ("agent_version", models.CharField(blank=True, editable=False, max_length=50)),
                ("model_version", models.CharField(blank=True, editable=False, max_length=50)),
                ("prompt_version", models.CharField(blank=True, editable=False, max_length=50)),
                ("event_hash", models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "audit trail record",
                "verbose_name_plural": "audit trail records",
                "ordering": ("-occurred_at",),
            },
        ),
    ]
