# Generated by Django 5.2.15 on 2026-07-29 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrailrecord",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="audittrailrecord",
            index=models.Index(
                fields=["resource_type", "resource_id", "-occurred_at"],
                name="audit_audit_resourc_5f86c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrailrecord",
            index=models.Index(
                fields=["actor", "-occurred_at"], name="audit_audit_actor_i_482dfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrailrecord",
            index=models.Index(
                fields=["event_type", "-occurred_at"], name="audit_audit_event_t_1e1faa_idx"
            ),
        ),
    ]
