# Generated by Django 5.2.15 on 2026-07-30 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
        ("orchestrator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("restricted", "Restricted"),
                            ("requires_approval", "Requires Approval"),
                            ("violated", "Violated"),
                            ("escalated", "Escalated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("restricted_list_match", models.BooleanField(default=False)),
                ("checks", models.JSONField(default=list)),
                ("violations", models.JSONField(default=list)),
                ("approval_required", models.BooleanField(default=False)),
                ("overridden", models.BooleanField(default=False)),
                ("review_rationale", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_result",
                        to="orchestrator.analysisrun",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("field", models.CharField(max_length=120)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("ne", "Not equal"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal"),
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal"),
                            ("in", "In"),
                            ("not_in", "Not in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_value", models.JSONField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("approval", "Approval"),
                            ("block", "Block"),
                        ],
                        default="block",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiskLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("metric", models.CharField(max_length=80, unique=True)),
                ("maximum", models.FloatField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("reduce", "Reduce size"),
                            ("escalate", "Escalate"),
                            ("block", "Block"),
                        ],
                        default="block",
                        max_length=20,
                    ),
                ),
                ("scope", models.CharField(default="portfolio", max_length=30)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiskValidationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("pass_with_warnings", "Pass With Warnings"),
                            ("reduce_size", "Reduce Size"),
                            ("hedge_required", "Hedge Required"),
                            ("block", "Block"),
                            ("escalate", "Escalate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("risk_metrics", models.JSONField(default=dict)),
                ("breaches", models.JSONField(default=list)),
                ("mitigations", models.JSONField(default=list)),
                ("hedge_suggestions", models.JSONField(default=list)),
                ("scenario_results", models.JSONField(default=dict)),
                ("rationale", models.TextField()),
                ("requires_escalation", models.BooleanField(default=False)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_validation",
                        to="orchestrator.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("portfolio_code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=24)),
                ("holdings", models.JSONField(default=list)),
                ("weights", models.JSONField(default=dict)),
                ("sector_exposures", models.JSONField(default=dict)),
                ("factor_exposures", models.JSONField(default=dict)),
                ("liquidity_metrics", models.JSONField(default=dict)),
                ("risk_metrics", models.JSONField(default=dict)),
                ("gross_leverage", models.FloatField(default=1.0)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["portfolio_code", "-as_of"], name="risk_compli_portfol_f81563_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("portfolio_code", "as_of", "version"),
                        name="uq_portfolio_snapshot_code_time_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RestrictedSecurity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("policy_reference", models.CharField(blank=True, max_length=120)),
                ("effective_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="market_data.ticker",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "is_active", "-effective_at"],
                        name="risk_compli_ticker__6505d4_idx",
                    )
                ],
            },
        ),
    ]
