# Generated by Django 5.2.15 on 2026-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceresult",
            name="rule_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="riskvalidationresult",
            name="rule_version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
