from .bear_system import BEAR_SYSTEM_PROMPT
from .bull_system import BULL_SYSTEM_PROMPT, PROMPT_VERSION
from .moderator_system import FINALIZE_SYSTEM_PROMPT, MODERATOR_SYSTEM_PROMPT

__all__ = [
    "BEAR_SYSTEM_PROMPT",
    "BULL_SYSTEM_PROMPT",
    "FINALIZE_SYSTEM_PROMPT",
    "MODERATOR_SYSTEM_PROMPT",
    "PROMPT_VERSION",
]
