# Generated by Django 5.2.15 on 2026-07-30 06:49

import apps.core.domain.enums
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("single", "Single security"),
                            ("watchlist", "Watchlist"),
                            ("sector", "Sector"),
                            ("universe", "Universe"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ingesting", "Ingesting"),
                            ("extracting_signals", "Extracting Signals"),
                            ("running_specialists", "Running Specialists"),
                            ("peer_analysis", "Peer Analysis"),
                            ("adversarial_review", "Adversarial Review"),
                            ("conviction_scoring", "Conviction Scoring"),
                            ("risk_validation", "Risk Validation"),
                            ("compliance_check", "Compliance Check"),
                            ("position_sizing", "Position Sizing"),
                            ("portfolio_optimization", "Portfolio Optimization"),
                            ("pm_synthesis", "Pm Synthesis"),
                            ("awaiting_pm_approval", "Awaiting Pm Approval"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default=apps.core.domain.enums.PipelineStatus["PENDING"],
                        max_length=40,
                    ),
                ),
                ("analysis_config", models.JSONField(default=dict)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("checkpoint_thread_id", models.CharField(max_length=255, unique=True)),
                ("current_stage", models.CharField(blank=True, max_length=60)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_runs",
                        to="market_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineStepResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("agent_version", models.CharField(blank=True, max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("step_name", models.CharField(max_length=80)),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("input_snapshot", models.JSONField(default=dict)),
                ("output_snapshot", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="orchestrator.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "attempt"),
            },
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["ticker", "-created_at"], name="orchestrato_ticker__a729de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["status", "-created_at"], name="orchestrato_status_c49098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestepresult",
            index=models.Index(
                fields=["analysis_run", "sequence", "status"],
                name="orchestrato_analysi_e6672e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinestepresult",
            constraint=models.UniqueConstraint(
                fields=("analysis_run", "step_name", "attempt"),
                name="uq_pipeline_step_run_name_attempt",
            ),
        ),
    ]
