# Generated by Django 5.2.15 on 2026-07-30 08:31

import apps.core.domain.enums
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="configuration_hash",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="data_cutoff_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="manifest_hash",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="run_manifest",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ingesting", "Ingesting"),
                    ("extracting_signals", "Extracting Signals"),
                    ("running_specialists", "Running Specialists"),
                    ("peer_analysis", "Peer Analysis"),
                    ("adversarial_review", "Adversarial Review"),
                    ("conviction_scoring", "Conviction Scoring"),
                    ("risk_validation", "Risk Validation"),
                    ("compliance_check", "Compliance Check"),
                    ("position_sizing", "Position Sizing"),
                    ("portfolio_optimization", "Portfolio Optimization"),
                    ("pm_synthesis", "Pm Synthesis"),
                    ("awaiting_pm_approval", "Awaiting Pm Approval"),
                    ("blocked", "Blocked"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default=apps.core.domain.enums.PipelineStatus["PENDING"],
                max_length=40,
            ),
        ),
    ]
