# Generated by Django 5.2.15 on 2026-07-30 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0002_companyprofile_available_at_and_more"),
        ("orchestrator", "0002_analysisrun_configuration_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="request_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("initiated_by", "idempotency_key"),
                name="uq_analysis_user_idempotency_key",
            ),
        ),
    ]
