# Generated by Django 5.2.15 on 2026-07-29 15:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("finnhub", "Finnhub"),
                            ("fred", "Federal Reserve Economic Data"),
                            ("sec_edgar", "SEC EDGAR"),
                            ("news_api", "NewsAPI"),
                            ("yfinance", "Yahoo Finance"),
                            ("alpha_vantage", "Alpha Vantage"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("supported_categories", models.JSONField(default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("requests_per_minute", models.PositiveIntegerField(default=60)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                (
                    "retry_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("stale_after_seconds", models.PositiveIntegerField(default=3600)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("priority", "source_type"),
            },
        ),
        migrations.CreateModel(
            name="RawInputObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("finnhub", "Finnhub"),
                            ("fred", "Federal Reserve Economic Data"),
                            ("sec_edgar", "SEC EDGAR"),
                            ("news_api", "NewsAPI"),
                            ("yfinance", "Yahoo Finance"),
                            ("alpha_vantage", "Alpha Vantage"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "data_category",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("ohlcv", "OHLCV"),
                            ("company_profile", "Company profile"),
                            ("financial_statement", "Financial statement"),
                            ("filing", "Regulatory filing"),
                            ("macro", "Macro indicator"),
                            ("news", "News"),
                            ("ownership", "Ownership"),
                            ("insider_transaction", "Insider transaction"),
                            ("peer_group", "Peer group"),
                            ("alternative", "Alternative data"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("entity_identifier", models.CharField(blank=True, db_index=True, max_length=120)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("raw_text", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(db_index=True)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("media_type", models.CharField(default="application/json", max_length=100)),
                ("schema_version", models.CharField(default="raw", max_length=30)),
                ("request_metadata", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("accepted", "Accepted"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                (
                    "source_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_inputs",
                        to="data_ingestion.datasourceconfiguration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedDataRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_quality_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "data_category",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("ohlcv", "OHLCV"),
                            ("company_profile", "Company profile"),
                            ("financial_statement", "Financial statement"),
                            ("filing", "Regulatory filing"),
                            ("macro", "Macro indicator"),
                            ("news", "News"),
                            ("ownership", "Ownership"),
                            ("insider_transaction", "Insider transaction"),
                            ("peer_group", "Peer group"),
                            ("alternative", "Alternative data"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("entity_identifier", models.CharField(blank=True, db_index=True, max_length=120)),
                ("canonical_key", models.CharField(blank=True, db_index=True, max_length=500)),
                ("normalized_payload", models.JSONField(default=dict)),
                ("schema_version", models.CharField(default="1.0", max_length=30)),
                ("language", models.CharField(default="en", max_length=10)),
                ("similarity_hash", models.CharField(blank=True, db_index=True, max_length=16)),
                ("lineage", models.JSONField(default=dict)),
                ("quality_issues", models.JSONField(blank=True, default=list)),
                ("quality_flags", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("accepted", "Accepted"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="normalized_records",
                        to="market_data.ticker",
                    ),
                ),
                (
                    "raw_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_records",
                        to="data_ingestion.rawinputobject",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="rawinputobject",
            index=models.Index(
                fields=["entity_identifier", "data_category", "-fetched_at"],
                name="data_ingest_entity__ccb7ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawinputobject",
            index=models.Index(
                fields=["status", "-fetched_at"], name="data_ingest_status_a66571_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawinputobject",
            constraint=models.UniqueConstraint(
                fields=("source_type", "data_category", "content_hash"),
                name="uq_raw_source_category_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizeddatarecord",
            index=models.Index(
                fields=["entity_identifier", "data_category", "-source_timestamp"],
                name="data_ingest_entity__d0c427_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizeddatarecord",
            index=models.Index(
                fields=["status", "-created_at"], name="data_ingest_status_bfe693_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="normalizeddatarecord",
            constraint=models.UniqueConstraint(
                fields=("source_type", "data_category", "content_hash"),
                name="uq_normalized_source_category_hash",
            ),
        ),
    ]
