# Generated by Django 5.2.15 on 2026-07-30 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="normalizeddatarecord",
            name="available_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="normalizeddatarecord",
            name="effective_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizeddatarecord",
            name="revision_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="normalizeddatarecord",
            name="vintage_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
