# Generated by Django 5.2.15 on 2026-09-07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0003_datapreparationrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceCategoryHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_category",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("ohlcv", "OHLCV"),
                            ("company_profile", "Company profile"),
                            ("financial_statement", "Financial statement"),
                            ("filing", "Regulatory filing"),
                            ("macro", "Macro indicator"),
                            ("news", "News"),
                            ("ownership", "Ownership"),
                            ("insider_transaction", "Insider transaction"),
                            ("peer_group", "Peer group"),
                            ("alternative", "Alternative data"),
                        ],
                        max_length=40,
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "source_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_health",
                        to="data_ingestion.datasourceconfiguration",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_config", "data_category"],
                        name="data_ingest_source__30af06_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_config", "data_category"),
                        name="unique_source_category_health",
                    )
                ],
            },
        ),
    ]
