import { BarChart3, FileText, Globe2, Newspaper } from "lucide-react";
import { Chip, Meter, Panel, SectionLabel } from "@/shared/ui";
import { EvidenceList } from "./evidence-list";
import type { FundamentalReportView, MacroReportView, SentimentReportView, TechnicalReportView } from "../types/specialist.types";

const bullets = (items: readonly string[]) => <ul className="mt-2 list-disc space-y-1 pl-5 text-xs leading-relaxed text-text-dim">{items.map((item) => <li key={item}>{item}</li>)}</ul>;

export function MacroReport({ report }: { report: MacroReportView }) { return <Panel><SectionLabel icon={Globe2}>Regime classification</SectionLabel><Chip color="var(--color-blue)">{report.regime}</Chip><p className="mt-3 text-xs leading-6 text-text-dim">{report.summary}</p>{bullets(report.points)}<EvidenceList items={report.evidence} /></Panel>; }
export function FundamentalReport({ report }: { report: FundamentalReportView }) { return <Panel><div className="flex justify-between"><SectionLabel icon={FileText}>Investment thesis</SectionLabel><Chip color="var(--color-blue)">Quality grade {report.grade}</Chip></div><p className="font-serif text-sm">{report.thesis}</p><div className="mt-4 grid grid-cols-2 gap-5"><div><h3 className="font-mono text-[10px] text-green uppercase">Bull drivers</h3>{bullets(report.bullDrivers)}</div><div><h3 className="font-mono text-[10px] text-red uppercase">Bear drivers</h3>{bullets(report.bearDrivers)}</div></div><div className="mt-4"><SectionLabel>Fair value range</SectionLabel><p className="font-mono text-xs">${report.fairValue.low} — <span className="text-amber">${report.fairValue.mid}</span> — ${report.fairValue.high}</p></div><EvidenceList items={report.evidence} /></Panel>; }
export function TechnicalReport({ report }: { report: TechnicalReportView }) { return <Panel><SectionLabel icon={BarChart3}>Trend state</SectionLabel><div className="mb-4 flex gap-7">{Object.entries(report.trend).map(([period, value]) => <div key={period}><p className="font-mono text-[9px] text-text-faint uppercase">{period}</p><p className="font-mono text-xs text-green">{value}</p></div>)}</div><SectionLabel>Momentum</SectionLabel><Meter className="mb-4 max-w-72" value={report.momentum} /><div className="flex gap-7 font-mono text-xs"><span>Support <span className="text-text-dim">${report.levels.support}</span></span><span>Resistance <span className="text-text-dim">${report.levels.resistance}</span></span></div>{bullets(report.flags)}<EvidenceList items={report.evidence} /></Panel>; }
export function SentimentReport({ report }: { report: SentimentReportView }) { return <Panel><SectionLabel icon={Newspaper}>Sentiment score</SectionLabel><Meter className="max-w-80" value={report.score + 100} limit={200} /><p className="mt-1 font-mono text-[10px] text-text-dim">Score: {report.score > 0 ? "+" : ""}{report.score} / 100 · {report.direction}</p><Chip className="mt-4" color="var(--color-amber)">Attention: {report.attention}</Chip><SectionLabel className="mt-4">Event tags</SectionLabel><div className="flex flex-wrap gap-2">{report.tags.map((tag) => <Chip key={tag}>{tag}</Chip>)}</div><EvidenceList items={report.evidence} /></Panel>; }
